name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
    - pytorch-lightning==1.7.7
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - einops==0.3.0
    - transformers==4.19.2
    - open_clip_torch==2.7.0
    - -e .
